In [2]:
import numpy as np
import pandas as pd

Q1. Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [38]:
def alexandreTheophileVandermonde(ip, N, increasing = False):
    if increasing!=True:
        print("increasing:")
        print(np.array([i**j for i in ip for j in range(N)]).reshape(len(ip), N))
    else:
        print("decreasing:")
        print(np.array([i**(N-j-1) for i in ip for j in range(N)]).reshape(len(ip),N))
        
ip = [1,2,3]
N = 5

alexandreTheophileVandermonde(ip, N, increasing = False)
print("\n")
alexandreTheophileVandermonde(ip, N, increasing = True)

increasing:
[[ 1  1  1  1  1]
 [ 1  2  4  8 16]
 [ 1  3  9 27 81]]


decreasing:
[[ 1  1  1  1  1]
 [16  8  4  2  1]
 [81 27  9  3  1]]


Q2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: The moving average sequence has n-k+1 elements as shown below. The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [65]:
ip = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] #window
k = 3 #window size

def movingWindow(ip, k):
    n = len(ip)
    print('The moving average sequence size is, (n-k+1) =', n-k+1, "\n")
    #print(ip[0:(n-k+1)])
    
    if (n-k+1) > 1:
        mw = [sum(ip[i:(i+k)])/3 for i in range(n-k+1)]
        for i,j in enumerate(mw):
            print('y{} = {}'.format(i+1,j))
    else:
        print('invalid')

movingWindow(ip, k)

The moving average sequence size is, (n-k+1) = 11 

y1 = 5.0
y2 = 4.666666666666667
y3 = 5.666666666666667
y4 = 6.666666666666667
y5 = 9.666666666666666
y6 = 28.666666666666668
y7 = 49.333333333333336
y8 = 72.66666666666667
y9 = 84.0
y10 = 93.33333333333333
y11 = 116.33333333333333
